// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aula13_continuacaoEF.csproj;

#nullable disable

namespace aula13_continuacaoEF.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230510232244_InsertTwoNewUsersAndOneProduct")]
    partial class InsertTwoNewUsersAndOneProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("aula13_continuacaoEF.Domain.Person", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .HasColumnType("TEXT");

                b.Property<string>("Telefone")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("People");
            });

            modelBuilder.Entity("aula13_continuacaoEF.Domain.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Description")
                    .HasColumnType("TEXT");

                b.Property<string>("Price")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.ToTable("Products");
            });
        #pragma warning restore 612, 618
        }
    }
}
